name: influx
description: "Budgeting app"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_lucide: ^1.11.0
  supabase_flutter: ^2.16.0
  flutter_dotenv: ^6.0.1
  flutter_svg: ^2.3.0
  fl_chart: ^1.2.0
  intl: any
  riverpod: ^3.3.2
  flutter_riverpod: ^3.3.2
  qr_flutter: ^4.1.0
  mobile_scanner: ^7.4.0
  image_picker: ^1.2.0
  google_mlkit_text_recognition: ^0.16.0
  refresh_rate: ^1.0.2
  flutter_launcher_icons: ^0.14.4
  pinput: ^6.0.2
  package_info_plus: ^10.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo/
    - assets/icon/
    - assets/icon.png
    - .env

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/InterVariable.ttf

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21